server:
  port: 8080

spring:
  application:
    name: crudProduit

  # Configuration PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/crudProduitSprint
    username: postgres
    password: passer
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update         # crée/actualise les tables automatiquement
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# OpenAPI / Swagger / Redoc
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  redoc:
    path: /redoc.html
